-- Automatically generated by Gen AI
-- Description: Inserts the 'driver_registration_active' flag into the system_feature_flags table.

INSERT INTO public.system_feature_flags (id, is_active)
VALUES ('driver_registration_active', false)
ON CONFLICT (id) DO UPDATE SET is_active = EXCLUDED.is_active;
