-- Migration: 20260617000000_gescape_flight_anchored_model.sql
-- G-Escape: flight-anchored crowdfunding model for Caribbean packages.
--
-- Architecture shift from the existing travel_packages (standalone, admin-curated):
--   flight_blocks is the MASTER CONSTRAINT — a block of seats on a single departure.
--   Multiple escape_packages share one flight_block (different villa options, same plane).
--   The flight only departs if allocated_seats >= tipping_point_seats by cancel_deadline.
--   Payment is PRE-AUTHORIZED (not captured) at booking time.
--   Capture happens only when the flight is CONFIRMED (tipping point reached).
--   If CANCELLED, all pre-auths are automatically voided.
--
-- Financial model:
--   Price = C_flight + C_lodging + F_driver_trinidad + F_driver_destination + M_platform
--   Platform margin = 19% of (Price - costs)
--   Driver loyalty rebate = 3% of (Price - costs), paid to drivers with 5-star rating

BEGIN;

-- ── 1. Driver zone rates (fixed payouts, not percentages) ────────────────────
--
-- Driver costs are locked in as hard cost inputs before the platform margin
-- is calculated. A trip from Cedros to Piarco cannot eat into the package margin.
-- Admin sets these rates; they are read by the pricing engine when compiling packages.

CREATE TABLE IF NOT EXISTS public.driver_zone_rates (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    zone_name    TEXT NOT NULL UNIQUE,
    description  TEXT NOT NULL,
    payout_cents INTEGER NOT NULL CHECK (payout_cents > 0),
    typical_distance_km NUMERIC,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.driver_zone_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access driver_zone_rates"
    ON public.driver_zone_rates FOR ALL
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Authenticated read driver_zone_rates"
    ON public.driver_zone_rates FOR SELECT
    USING (auth.role() = 'authenticated');

-- Seed with real T&T + Caribbean airport transfer zones (TTD cents)
INSERT INTO public.driver_zone_rates (zone_name, description, payout_cents, typical_distance_km) VALUES
    ('trinidad_west_piarco',   'West Trinidad (POS / Diego Martin / Westmoorings) → Piarco', 8000,  25),
    ('trinidad_central_piarco','Central Trinidad (Chaguanas / Couva) → Piarco',               9500,  35),
    ('trinidad_south_piarco',  'South Trinidad (San Fernando / Point Fortin) → Piarco',       13500, 55),
    ('trinidad_east_piarco',   'East Trinidad (Arima / Sangre Grande) → Piarco',              5500,  18),
    ('tobago_airport_crown',   'ANR Robinson Airport → Crown Point / Store Bay',              3000,   8),
    ('tobago_airport_scarborough','ANR Robinson Airport → Scarborough / Bon Accord',          5500,  15),
    ('tobago_airport_north',   'ANR Robinson Airport → North Tobago (Speyside / Charlotteville)', 12000, 35),
    ('barbados_grantley_south','Grantley Adams Airport → South Coast (St Lawrence Gap)',      4200,  12),
    ('barbados_grantley_west', 'Grantley Adams Airport → West Coast (Holetown)',              6500,  22),
    ('grenada_local',          'Maurice Bishop Airport → Grand Anse / St George''s',          3500,  10),
    ('antigua_vc_bird',        'VC Bird Airport → English Harbour / Nelson''s Dockyard',      5500,  15),
    ('st_kitts_golden_rock',   'Golden Rock Airport → Basseterre / South Peninsula',          4000,  12)
ON CONFLICT (zone_name) DO NOTHING;

-- ── 2. Flight blocks (master departure constraint) ────────────────────────────
--
-- Created by admin or auto-generated by platform_intelligence.
-- status POOLING   → accepting pre-auth bookings (seats being pooled)
-- status CONFIRMED → tipping_point_seats reached; all pre-auths captured; flight goes
-- status CANCELLED → deadline passed without tipping point; all pre-auths voided

CREATE TABLE IF NOT EXISTS public.flight_blocks (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    origin_code           TEXT NOT NULL DEFAULT 'POS',
    destination_code      TEXT NOT NULL,
    destination_name      TEXT NOT NULL,
    departure_time        TIMESTAMPTZ NOT NULL,
    return_time           TIMESTAMPTZ,
    aircraft_type         TEXT DEFAULT 'CAL ATR 72-600',
    total_capacity_seats  INTEGER NOT NULL DEFAULT 68,
    allocated_seats       INTEGER NOT NULL DEFAULT 0,
    tipping_point_seats   INTEGER NOT NULL DEFAULT 35,
    flight_cost_per_seat_cents INTEGER NOT NULL,
    airline_merchant_id   UUID REFERENCES public.merchants(id),
    status                TEXT NOT NULL DEFAULT 'POOLING'
                          CHECK (status IN ('POOLING', 'CONFIRMED', 'CANCELLED')),
    cancel_deadline       TIMESTAMPTZ,
    confirmed_at          TIMESTAMPTZ,
    notes                 TEXT,
    created_by            UUID REFERENCES auth.users(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT seats_valid CHECK (allocated_seats >= 0 AND allocated_seats <= total_capacity_seats)
);

CREATE INDEX idx_flight_blocks_departure ON public.flight_blocks(departure_time)
    WHERE status = 'POOLING';

ALTER TABLE public.flight_blocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access flight_blocks"
    ON public.flight_blocks FOR ALL
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Authenticated read flight_blocks"
    ON public.flight_blocks FOR SELECT
    USING (auth.role() = 'authenticated');

-- ── 3. Lodging nodes (hotel/villa inventory) ──────────────────────────────────
--
-- Each lodging node has strict guest bounds enforced at booking time.
-- location_zone links to driver_zone_rates for fixed driver cost calculation.
-- requires_verification = TRUE → "Request to Book" mode (card auth only, 2h manual confirm)

CREATE TABLE IF NOT EXISTS public.lodging_nodes (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id              UUID REFERENCES public.merchants(id),
    name                     TEXT NOT NULL,
    destination_code         TEXT NOT NULL,
    location_zone            TEXT NOT NULL REFERENCES public.driver_zone_rates(zone_name),
    min_guests               INTEGER NOT NULL DEFAULT 1 CHECK (min_guests >= 1),
    max_guests               INTEGER NOT NULL DEFAULT 6 CHECK (max_guests >= min_guests),
    nights                   INTEGER NOT NULL DEFAULT 2 CHECK (nights >= 1),
    base_price_per_night_cents INTEGER NOT NULL CHECK (base_price_per_night_cents > 0),
    cover_image_url          TEXT,
    description              TEXT,
    amenities                TEXT[],
    requires_verification    BOOLEAN NOT NULL DEFAULT FALSE,
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    created_by               UUID REFERENCES auth.users(id),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.lodging_nodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access lodging_nodes"
    ON public.lodging_nodes FOR ALL
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Authenticated read active lodging_nodes"
    ON public.lodging_nodes FOR SELECT
    USING (auth.role() = 'authenticated' AND is_active = TRUE);

-- ── 4. Escape packages (client-facing compiled offer) ─────────────────────────
--
-- Joins flight_block + lodging_node into a consumer-facing bundle.
-- price_per_person_cents is the full retail price.
-- Wholesale cost columns are admin-only — never sent to the client app.

CREATE TABLE IF NOT EXISTS public.escape_packages (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    flight_block_id             UUID NOT NULL REFERENCES public.flight_blocks(id),
    lodging_node_id             UUID NOT NULL REFERENCES public.lodging_nodes(id),
    package_name                TEXT NOT NULL,
    tagline                     TEXT,
    cover_image_url             TEXT,
    -- Retail price (what the rider pays)
    price_per_person_cents      INTEGER NOT NULL CHECK (price_per_person_cents > 0),
    -- Cost stack (admin-only visibility — never exposed via client API)
    flight_cost_per_person_cents    INTEGER NOT NULL,
    lodging_cost_per_person_cents   INTEGER NOT NULL,
    driver_origin_zone          TEXT REFERENCES public.driver_zone_rates(zone_name),
    driver_origin_cost_cents    INTEGER NOT NULL DEFAULT 0,
    driver_destination_zone     TEXT REFERENCES public.driver_zone_rates(zone_name),
    driver_destination_cost_cents INTEGER NOT NULL DEFAULT 0,
    platform_margin_cents       INTEGER NOT NULL,
    loyalty_rebate_cents        INTEGER NOT NULL DEFAULT 0,
    is_active                   BOOLEAN NOT NULL DEFAULT TRUE,
    created_by                  UUID REFERENCES auth.users(id),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Margin guard: retail must always exceed costs
    CONSTRAINT margin_positive CHECK (
        price_per_person_cents > (
            flight_cost_per_person_cents +
            lodging_cost_per_person_cents +
            driver_origin_cost_cents +
            driver_destination_cost_cents
        )
    )
);

CREATE INDEX idx_escape_packages_active ON public.escape_packages(flight_block_id)
    WHERE is_active = TRUE;

ALTER TABLE public.escape_packages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access escape_packages"
    ON public.escape_packages FOR ALL
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Authenticated read active escape_packages"
    ON public.escape_packages FOR SELECT
    USING (auth.role() = 'authenticated' AND is_active = TRUE);

-- ── 5. Package reservations (10-minute holds + confirmed seats) ───────────────
--
-- state machine:
--   PENDING_HOLD   — transaction just started, verification in progress
--   ACTIVE_HOLD    — seats locked, payment pre-auth window open (10 minutes)
--   CAPTURED       — pre-auth captured, awaiting flight tipping point
--   CONFIRMED      — flight confirmed; booking is solid; ground transfers created
--   RELEASED       — hold expired without payment; seats returned to flight block
--   CANCELLED      — flight cancelled or rider cancelled; pre-auth voided

CREATE TABLE IF NOT EXISTS public.package_reservations (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    escape_package_id     UUID NOT NULL REFERENCES public.escape_packages(id),
    flight_block_id       UUID NOT NULL REFERENCES public.flight_blocks(id),
    rider_id              UUID NOT NULL REFERENCES auth.users(id),
    guest_count           INTEGER NOT NULL DEFAULT 1,
    total_price_cents     INTEGER NOT NULL,
    status                TEXT NOT NULL DEFAULT 'PENDING_HOLD'
                          CHECK (status IN (
                              'PENDING_HOLD','ACTIVE_HOLD','CAPTURED',
                              'CONFIRMED','RELEASED','CANCELLED'
                          )),
    -- Payment
    payment_method        TEXT NOT NULL DEFAULT 'stripe'
                          CHECK (payment_method IN ('stripe','wipay','wallet')),
    stripe_payment_intent_id TEXT,
    wipay_auth_token      TEXT,
    -- Hold timing
    hold_expires_at       TIMESTAMPTZ,
    captured_at           TIMESTAMPTZ,
    confirmed_at          TIMESTAMPTZ,
    -- Ground transfer
    pickup_address        TEXT,
    pickup_lat            DOUBLE PRECISION,
    pickup_lng            DOUBLE PRECISION,
    trinidad_transfer_ride_id    UUID REFERENCES public.rides(id),
    destination_transfer_ride_id UUID REFERENCES public.rides(id),
    -- Passenger manifest
    passenger_names       JSONB NOT NULL DEFAULT '[]',
    passport_image_url    TEXT,
    special_requests      TEXT,
    -- Capital reserve
    reserve_amount_cents  INTEGER,
    -- Internal ref
    booking_ref           TEXT UNIQUE DEFAULT upper(substr(md5(gen_random_uuid()::text), 1, 8)),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pkg_reservations_rider ON public.package_reservations(rider_id);
CREATE INDEX idx_pkg_reservations_flight ON public.package_reservations(flight_block_id, status);
CREATE INDEX idx_pkg_reservations_expired ON public.package_reservations(hold_expires_at)
    WHERE status = 'ACTIVE_HOLD';

ALTER TABLE public.package_reservations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Rider sees own reservations"
    ON public.package_reservations FOR SELECT
    USING (rider_id = auth.uid());

CREATE POLICY "Admin full access package_reservations"
    ON public.package_reservations FOR ALL
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ── 6. secure_escape_booking RPC ─────────────────────────────────────────────
--
-- Atomic pessimistic lock: locks flight_blocks row FOR UPDATE, validates both
-- lodging occupancy rules and seat availability, then creates a 10-minute hold.
-- Returns success, message, reservation_id, total_price_cents, hold_expires_at.

CREATE OR REPLACE FUNCTION public.secure_escape_booking(
    p_escape_package_id  UUID,
    p_rider_id           UUID,
    p_guest_count        INTEGER,
    p_payment_method     TEXT DEFAULT 'stripe',
    p_pickup_address     TEXT DEFAULT NULL,
    p_pickup_lat         DOUBLE PRECISION DEFAULT NULL,
    p_pickup_lng         DOUBLE PRECISION DEFAULT NULL,
    p_passenger_names    JSONB DEFAULT '[]',
    p_special_requests   TEXT DEFAULT NULL
)
RETURNS TABLE (
    success          BOOLEAN,
    message          TEXT,
    reservation_id   UUID,
    total_price_cents INTEGER,
    hold_expires_at  TIMESTAMPTZ,
    seats_remaining  INTEGER,
    requires_verification BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_flight_id          UUID;
    v_lodging_id         UUID;
    v_min_guests         INTEGER;
    v_max_guests         INTEGER;
    v_seats_avail        INTEGER;
    v_flight_status      TEXT;
    v_price_per_person   INTEGER;
    v_requires_verif     BOOLEAN;
    v_total_price        INTEGER;
    v_reservation_id     UUID;
    v_hold_expires       TIMESTAMPTZ;
    v_reserve_cents      INTEGER;
BEGIN
    -- 1. Fetch package (fail fast if inactive)
    SELECT ep.flight_block_id, ep.lodging_node_id, ep.price_per_person_cents
    INTO v_flight_id, v_lodging_id, v_price_per_person
    FROM public.escape_packages ep
    WHERE ep.id = p_escape_package_id AND ep.is_active = TRUE;

    IF NOT FOUND THEN
        RETURN NEXT(FALSE, 'Package not found or no longer available.',
                    NULL, NULL, NULL, NULL, NULL);
        RETURN;
    END IF;

    -- 2. Validate lodging occupancy rules
    SELECT ln.min_guests, ln.max_guests, ln.requires_verification
    INTO v_min_guests, v_max_guests, v_requires_verif
    FROM public.lodging_nodes ln
    WHERE ln.id = v_lodging_id;

    IF p_guest_count < v_min_guests OR p_guest_count > v_max_guests THEN
        RETURN NEXT(
            FALSE,
            'Guest count must be between ' || v_min_guests || ' and ' || v_max_guests || ' for this property.',
            NULL, NULL, NULL, NULL, v_requires_verif
        );
        RETURN;
    END IF;

    -- 3. Lock flight block row — prevents race conditions during concurrent buys
    SELECT (fb.total_capacity_seats - fb.allocated_seats), fb.status
    INTO v_seats_avail, v_flight_status
    FROM public.flight_blocks fb
    WHERE fb.id = v_flight_id
    FOR UPDATE;

    IF v_flight_status = 'CANCELLED' THEN
        RETURN NEXT(FALSE, 'This flight has been cancelled.', NULL, NULL, NULL, 0, NULL);
        RETURN;
    END IF;

    IF v_seats_avail < p_guest_count THEN
        RETURN NEXT(
            FALSE,
            'Only ' || v_seats_avail || ' seat(s) remaining on this flight.',
            NULL, NULL, NULL, v_seats_avail, NULL
        );
        RETURN;
    END IF;

    -- 4. Atomically allocate seats
    UPDATE public.flight_blocks
    SET allocated_seats = allocated_seats + p_guest_count,
        updated_at = now()
    WHERE id = v_flight_id;

    -- 5. Compute pricing
    v_total_price  := v_price_per_person * p_guest_count;
    v_reserve_cents := ROUND(v_total_price * 0.015);
    v_hold_expires := now() + INTERVAL '10 minutes';

    -- 6. Create the hold record
    INSERT INTO public.package_reservations (
        escape_package_id, flight_block_id, rider_id, guest_count,
        total_price_cents, status, payment_method, hold_expires_at,
        pickup_address, pickup_lat, pickup_lng,
        passenger_names, special_requests, reserve_amount_cents
    ) VALUES (
        p_escape_package_id, v_flight_id, p_rider_id, p_guest_count,
        v_total_price, 'ACTIVE_HOLD', p_payment_method, v_hold_expires,
        p_pickup_address, p_pickup_lat, p_pickup_lng,
        p_passenger_names, p_special_requests, v_reserve_cents
    ) RETURNING id INTO v_reservation_id;

    RETURN NEXT(
        TRUE,
        'Seats held. Complete payment within 10 minutes to secure your escape.',
        v_reservation_id,
        v_total_price,
        v_hold_expires,
        v_seats_avail - p_guest_count,
        v_requires_verif
    );
    RETURN;
END;
$$;

REVOKE ALL ON FUNCTION public.secure_escape_booking(UUID,UUID,INTEGER,TEXT,TEXT,DOUBLE PRECISION,DOUBLE PRECISION,JSONB,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.secure_escape_booking(UUID,UUID,INTEGER,TEXT,TEXT,DOUBLE PRECISION,DOUBLE PRECISION,JSONB,TEXT)
    TO service_role, authenticated;

-- ── 7. release_expired_holds RPC (called by pg_cron every minute) ─────────────

CREATE OR REPLACE FUNCTION public.release_expired_holds()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_released INTEGER := 0;
    v_rec      RECORD;
BEGIN
    FOR v_rec IN
        SELECT id, flight_block_id, guest_count
        FROM public.package_reservations
        WHERE status = 'ACTIVE_HOLD'
          AND hold_expires_at < now()
        FOR UPDATE SKIP LOCKED
    LOOP
        -- Return seats to the flight block
        UPDATE public.flight_blocks
        SET allocated_seats = GREATEST(0, allocated_seats - v_rec.guest_count),
            updated_at = now()
        WHERE id = v_rec.flight_block_id;

        -- Mark reservation as released
        UPDATE public.package_reservations
        SET status = 'RELEASED', updated_at = now()
        WHERE id = v_rec.id;

        v_released := v_released + 1;
    END LOOP;

    RETURN v_released;
END;
$$;

REVOKE ALL ON FUNCTION public.release_expired_holds() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.release_expired_holds() TO service_role;

-- ── 8. check_flight_tipping_points RPC (called daily at T-3 days) ─────────────
--
-- For each POOLING block past its cancel_deadline:
--   - If allocated_seats >= tipping_point_seats → CONFIRMED (flight goes)
--   - Otherwise → CANCELLED (seats released, pre-auths voided)

CREATE OR REPLACE FUNCTION public.check_flight_tipping_points()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_block RECORD;
BEGIN
    FOR v_block IN
        SELECT id, tipping_point_seats, allocated_seats, departure_time
        FROM public.flight_blocks
        WHERE status = 'POOLING'
          AND cancel_deadline <= now()
        FOR UPDATE
    LOOP
        IF v_block.allocated_seats >= v_block.tipping_point_seats THEN
            UPDATE public.flight_blocks
            SET status = 'CONFIRMED', confirmed_at = now(), updated_at = now()
            WHERE id = v_block.id;

            UPDATE public.package_reservations
            SET status = 'CONFIRMED', confirmed_at = now(), updated_at = now()
            WHERE flight_block_id = v_block.id AND status = 'CAPTURED';
        ELSE
            UPDATE public.flight_blocks
            SET status = 'CANCELLED', updated_at = now()
            WHERE id = v_block.id;

            -- Return seats and cancel reservations
            UPDATE public.package_reservations
            SET status = 'CANCELLED', updated_at = now()
            WHERE flight_block_id = v_block.id AND status IN ('ACTIVE_HOLD', 'CAPTURED');

            UPDATE public.flight_blocks
            SET allocated_seats = 0, updated_at = now()
            WHERE id = v_block.id;
        END IF;
    END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.check_flight_tipping_points() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_flight_tipping_points() TO service_role;

-- ── 9. Admin RPC: upsert escape package ──────────────────────────────────────

CREATE OR REPLACE FUNCTION public.admin_upsert_escape_package(
    p_id                        UUID DEFAULT NULL,
    p_flight_block_id           UUID DEFAULT NULL,
    p_lodging_node_id           UUID DEFAULT NULL,
    p_package_name              TEXT DEFAULT NULL,
    p_tagline                   TEXT DEFAULT NULL,
    p_cover_image_url           TEXT DEFAULT NULL,
    p_price_per_person_cents    INTEGER DEFAULT NULL,
    p_flight_cost_per_person_cents  INTEGER DEFAULT NULL,
    p_lodging_cost_per_person_cents INTEGER DEFAULT NULL,
    p_driver_origin_zone        TEXT DEFAULT NULL,
    p_driver_origin_cost_cents  INTEGER DEFAULT NULL,
    p_driver_destination_zone   TEXT DEFAULT NULL,
    p_driver_destination_cost_cents INTEGER DEFAULT NULL,
    p_platform_margin_cents     INTEGER DEFAULT NULL,
    p_loyalty_rebate_cents      INTEGER DEFAULT NULL,
    p_is_active                 BOOLEAN DEFAULT TRUE
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id UUID;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
    ) THEN
        RAISE EXCEPTION 'Unauthorized';
    END IF;

    IF p_id IS NOT NULL THEN
        UPDATE public.escape_packages SET
            flight_block_id               = COALESCE(p_flight_block_id, flight_block_id),
            lodging_node_id               = COALESCE(p_lodging_node_id, lodging_node_id),
            package_name                  = COALESCE(p_package_name, package_name),
            tagline                       = COALESCE(p_tagline, tagline),
            cover_image_url               = COALESCE(p_cover_image_url, cover_image_url),
            price_per_person_cents        = COALESCE(p_price_per_person_cents, price_per_person_cents),
            flight_cost_per_person_cents  = COALESCE(p_flight_cost_per_person_cents, flight_cost_per_person_cents),
            lodging_cost_per_person_cents = COALESCE(p_lodging_cost_per_person_cents, lodging_cost_per_person_cents),
            driver_origin_zone            = COALESCE(p_driver_origin_zone, driver_origin_zone),
            driver_origin_cost_cents      = COALESCE(p_driver_origin_cost_cents, driver_origin_cost_cents),
            driver_destination_zone       = COALESCE(p_driver_destination_zone, driver_destination_zone),
            driver_destination_cost_cents = COALESCE(p_driver_destination_cost_cents, driver_destination_cost_cents),
            platform_margin_cents         = COALESCE(p_platform_margin_cents, platform_margin_cents),
            loyalty_rebate_cents          = COALESCE(p_loyalty_rebate_cents, loyalty_rebate_cents),
            is_active                     = COALESCE(p_is_active, is_active),
            updated_at = now()
        WHERE id = p_id
        RETURNING id INTO v_id;
    ELSE
        INSERT INTO public.escape_packages (
            flight_block_id, lodging_node_id, package_name, tagline, cover_image_url,
            price_per_person_cents, flight_cost_per_person_cents, lodging_cost_per_person_cents,
            driver_origin_zone, driver_origin_cost_cents,
            driver_destination_zone, driver_destination_cost_cents,
            platform_margin_cents, loyalty_rebate_cents, is_active, created_by
        ) VALUES (
            p_flight_block_id, p_lodging_node_id, p_package_name, p_tagline, p_cover_image_url,
            p_price_per_person_cents, p_flight_cost_per_person_cents, p_lodging_cost_per_person_cents,
            p_driver_origin_zone, COALESCE(p_driver_origin_cost_cents, 0),
            p_driver_destination_zone, COALESCE(p_driver_destination_cost_cents, 0),
            p_platform_margin_cents, COALESCE(p_loyalty_rebate_cents, 0), p_is_active, auth.uid()
        ) RETURNING id INTO v_id;
    END IF;

    RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_upsert_escape_package FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_upsert_escape_package TO service_role, authenticated;

-- ── 10. pg_cron schedule: release expired holds every minute ─────────────────
--
-- Requires pg_cron extension. Supabase projects have it enabled.
-- If this fails, the release_expired_holds() function can also be called
-- from platform_intelligence on its 15-minute cycle.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        PERFORM cron.schedule(
            'release-expired-escape-holds',
            '* * * * *',
            $cron$SELECT public.release_expired_holds();$cron$
        );
        PERFORM cron.schedule(
            'check-escape-tipping-points',
            '0 6 * * *',
            $cron$SELECT public.check_flight_tipping_points();$cron$
        );
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL; -- pg_cron not available in this context; schedule via platform_intelligence
END;
$$;

COMMIT;
